package com.datamotion.Models;

import com.datamotion.DMWeb;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Getter;
import lombok.Setter;

/**
 * Attachment Model Class
 */
public class Attachment {	
	/**
	 * Attachment Base64 string
	 */
	@Getter @Setter
	private String AttachmentBase64;
	
	/**
	 * Attachment MIME Content Type tag
	 */
	@Getter @Setter
	private String ContentType;
	
	/**
	 * Attachment Filename
	 */
	@Getter @Setter
	private String FileName;
	
	/**
	 * Attachment byte array, generated when attachment is mapped through the constructor
	 */
	@Getter @Setter
	private byte[] Bytes;
	
	/**
	 * Constructor, maps input to class fields and generated byte array from Base64 string
	 * @param AB64 <code>String</code> Base64 string
	 * @param CT <code>String</code> MIME content type
	 * @param FN <code>String</code> file name
	 */
	@JsonCreator
	public Attachment(@JsonProperty("AttachmentBase64") String AB64,
			@JsonProperty("ContentType") String CT,
			@JsonProperty("FileName") String FN) {
		AttachmentBase64 = AB64;
		ContentType = CT;
		FN = FileName;
		DMWeb dmweb = new DMWeb();
		Bytes = dmweb.decodeBase64ToByteArray(AB64);
	}
}
