image: gradle:jdk8-slim

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - mapfile BuildConfiguration < BUILD

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - sed -i "s/version-num/${BuildConfiguration[0]}/g" build.gradle
    - gradle --build-cache -PmavenUser=$MavenUser -PmavenPass=$MavenPass assemble
    - gradle shadowJar -PmavenUser=$MavenUser -PmavenPass=$MavenPass
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - "build/libs/"

test:
  stage: test
  script: 
    #Write Config File from Environment Variables
    - echo $UserIdOrEmail > "userpass.txt"
    - echo $Password >> "userpass.txt"
    - cat userpass.txt
    #Execute Tests
    - gradle check -PmavenUser=$MavenUser -PmavenPass=$MavenPass
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  dependencies:
    - build

deploy:
  stage: deploy
  script: 
    - gradle publish -PmavenUser=$MavenUser -PmavenPass=$MavenPass
  only:
    - tags
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  environment:
    name: maven    
  dependencies:
    - build
    - test