version: 1.0.0.{build}

image: Visual Studio 2017

skip_commits:
    message: /\[ci skip\]/

before_build:
    - ps: $BUILDNUM = Get-Content -Path BUILDNUM
    - ps: (Get-Content -Path build.gradle).replace('version-num',$BUILDNUM) | Set-Content -Path build.gradle

build_script:
    - gradlew.bat --build-cache -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% assemble --info --no-daemon
    - gradlew.bat shadowJar -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% --info --no-daemon
    - gradlew.bat javadoc -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% --info --no-daemon

test_script:
    - ps: Write-Host 'Setting TLS version to 1.2'
    - ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
    - ps: $string = "{0}{1}{2}" -f $env:UserIdOrEmail,([Environment]::NewLine),$env:Password | Out-File -Encoding ascii userpass.txt
    - gradlew.bat check -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% --info --no-daemon
    
on_finish:
    # - ps: cat "$env:APPVEYOR_BUILD_FOLDER/build/test-results"
    - ps: $url = "https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID"
    - ps: echo $url
    - ps: >
        foreach($file in Get-ChildItem -Path "$env:APPVEYOR_BUILD_FOLDER/build/test-results" -Filter *.xml -Recurse) 
        {
            Write-Host $file.FullName
            $wc = New-Object 'System.Net.WebClient'
            $wc.UploadFile($url, $file.FullName)
        }

artifacts:
- path: build/libs
- path: build/docs

deploy_script:
    - ps: >-
        if($env:appveyor_repo_tag -eq 'True') 
        {
            iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
            cmd /c "appveyor-tools\secure-file -decrypt codesigning.asc.enc -secret $env:Secret"
            ls
            gpg --fast-import codesigning.asc
            
            $string = "signing.keyId={0}{1}signing.keypassword={2}" -f $env:KeyId,([Environment]::NewLine),$env:KeyPassword | Out-File -Encoding ascii $env:GRADLE_USER_HOME\gradle.properties

            #cmd /c "gradlew.bat sign publish -PmavenUser=$MavenUser -PmavenPass=$MavenPass"
            cmd /c "gradlew tasks"
            cmd /c "gradlew.bat sign -PmavenUser=$MavenUser -PmavenPass=$MavenPass"
            cmd /c "gradlew.bat publish -PmavenUser=$MavenUser -PmavenPass=$MavenPass"
        }