version: 1.0.{build}

image: Visual Studio 2017

before_build:
- ps: >-
    $BUILDNUM = Get-Content -Path BUILD
    (Get-Content -Path build.gradle).replace('version-num',$BUILDNUM) | Set-Content -Path build.gradle

build_script:
    - gradlew.bat --build-cache -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% assemble
    - gradlew.bat shadowJar -PmavenUser=%MavenUser% -PmavenPass=%MavenPass%
    - gradlew.bat javadoc -PmavenUser=%MavenUser% -PmavenPass=%MavenPass%

artifacts:
- path: build/libs
- path: build/docs

deploy_script:
    - gradlew.bat publish -PmavenUser=$MavenUser -PmavenPass=$MavenPass