version: 1.0.0.{build}

image: Visual Studio 2017

skip_commits:
    message: /\[ci skip\]/

before_build:
    - ps: $BUILDNUM = Get-Content -Path BUILDNUM
    - ps: (Get-Content -Path build.gradle).replace('version-num',$BUILDNUM) | Set-Content -Path build.gradle

build_script:
    - gradlew.bat --build-cache -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% assemble --info --no-daemon
    - gradlew.bat shadowJar -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% --info --no-daemon
    - gradlew.bat javadoc -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% --info --no-daemon

test_script:
    - ps: $string = "{0}{1}{2}" -f $env:UserIdOrEmail,([Environment]::NewLine),$env:Password | Out-File userpass.txt
    - ps: cat userpass.txt
    - gradlew.bat check -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% --info --no-daemon
    
on_finish:
    # - ps: cat "$env:APPVEYOR_BUILD_FOLDER/build/test-results"
    - ps: $url = "https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID"
    - ps: echo $url
    - ps: >
        Get-ChildItem -Path "$env:APPVEYOR_BUILD_FOLDER/build/test-results" -Filter *.xml -Recurse -File -Name | ForEach-Object {
            echo $_.FullName
            $wc = New-Object 'System.Net.WebClient'
            $wc.UploadFile($url, $_.FullName)
        }

artifacts:
- path: build/libs
- path: build/docs

deploy_script:
    - ps: >-
        if($env:appveyor_repo_tag -eq 'True') {
            cmd gradlew.bat publish -PmavenUser=$MavenUser -PmavenPass=$MavenPass
        }