version: 1.0.0.{build}

image: Visual Studio 2017

before_build:
    - ps: $BUILDNUM = Get-Content -Path BUILDNUM
    - ps: (Get-Content -Path build.gradle).replace('version-num',$BUILDNUM) | Set-Content -Path build.gradle

build_script:
    - gradlew.bat --build-cache -PmavenUser=%MavenUser% -PmavenPass=%MavenPass% assemble
    - gradlew.bat shadowJar -PmavenUser=%MavenUser% -PmavenPass=%MavenPass%
    - gradlew.bat javadoc -PmavenUser=%MavenUser% -PmavenPass=%MavenPass%

test_script:
    - ps: $string = "{0}{1}{2}" -f $env:UserIdOrEmail,([Environment]::NewLine),$env:Password | Out-File userpass.txt
    - ps: cat userpass.txt
    - gradlew.bat check -PmavenUser=%MavenUser% -PmavenPass=%MavenPass%
    - ps: $wc = New-Object 'System.Net.WebClient'
    - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", "C:/projects/library/build/reports/tests/test/index.html")
artifacts:
- path: build/libs
- path: build/docs

deploy_script:
    - ps: >-
        if($env:appveyor_repo_tag -eq 'True') {
            cmd gradlew.bat publish -PmavenUser=$MavenUser -PmavenPass=$MavenPass
        }